services:
  db:
    image: postgres:16-alpine
    container_name: pg_laptop_shop
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: laptop_shop
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c timezone=Asia/Ho_Chi_Minh
      -c log_timezone=Asia/Ho_Chi_Minh

volumes:
  postgres_data: